#!/usr/bin/env node

const creds = require('./creds.json');
const https = require('https');

const headers = {
    'Connection': 'keep-alive',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
    'Origin': 'http://vpl-wireless.vpl.ca',
    'Upgrade-Insecure-Requests': '1',
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/74.0.3729.169 Chrome/74.0.3729.169 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Referer': 'http://vpl-wireless.vpl.ca/cPortal?cmd=login&mac=9c%3Ab6%3Ad0%3Ad6%3A52%3A57&essid=VPL&ip=209.52.108.67&apname=TSN-AR-J2&apmac=04%3Abd%3A88%3Ace%3A0c%3A0a&vcname=TSN-AR-CTRL&switchip=captiveportal-login.vpl.ca&url=https%3A%2F%2Fvpl.ca%2F',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9,fr;q=0.8,fr-CA;q=0.7',
    'Cookie': '_ga=GA1.2.1292549263.1560198240'
};

const data = `user=${creds.user}&password=${creds.pass}&cmd=authenticate&cmd=login&mac=9c%3Ab6%3Ad0%3Ad6%3A52%3A57&ip=209.52.108.67&essid=VPL&url=https%3A%2F%2Fvpl.ca%2F&Login=Accept+%26+Connect`;

const options = {
  hostname: 'captiveportal-login.vpl.ca',
  // port: 443,
  path: '/cgi-bin/login',
  method: 'POST',
  headers
}

const req = https.request(options, (res) => {
  console.log(`statusCode: ${res.statusCode}`)

  res.on('data', (data) => {
    process.stdout.write(data)
  })
})

req.on('error', (error) => {
  console.error(error)
})

req.write(data)
req.end()
