#!/bin/bash
# Adds PS1 color for the root user of a server, microcomputer, or other device that I access for the first time over ssh
# Run this after you've added your non-root sudo-capable user

for d in /home/* ; do
	echo "export PS1='\[\033[38;5;13m\][\u@\h \[$(tput sgr0)\]\[\033[38;5;6m\]\w\[$(tput sgr0)\]\[\033[38;5;13m\]]\[$(tput sgr0)\]\[\033[38;5;15m\]\\$\[$(tput sgr0)\] '" >> $d/.bash_profile
done
